### PR TITLE
Setup contributing.md, lint code and implement lock file rule in gitignore

### PR DESCRIPTION
**Pull request by arihantbansal**
added steps in contributing.md, ran eslint, and added `package-lock.json` to `.gitignore` to avoid lock file conflicts.

### CODE REVIEW

**Review by Eversmile12 — CHANGES_REQUESTED** [review]
Can you move tabs to 4 spaces instead of 2 in prettier?

**Comment by arihantbansal** [comment]
> Can you move tabs to 4 spaces instead of 2 in prettier?

Should I setup prettier for the dev environment?

**Comment by arihantbansal** [comment]
@Eversmile12 added prettier and updated everything.

**Comment by Eversmile12** [comment]
lgtm

**Pull request merged**
