### PR TITLE
clean up git folder after dapp creation

### PR DESCRIPTION
**Pull request by Hussainzz**
remove the .git folder once dapp is created by `create-web3-dapp`

### CODE REVIEW

**Review by Eversmile12 — APPROVED** [review]
Thank you!

**Comment by Eversmile12** [comment]
lgtm

**Comment by Hussainzz** [comment]
It does keep the .git folder  after dapp creation.... 
Shows git changes

**Comment by Hussainzz** [comment]
@Eversmile12 why this changes not merged ?

**Pull request closed without merging**
